include:
  - board: bmp_boost
    shield: watahaku_17_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: watahaku_17_left_central
  - board: bmp_boost
    shield: watahaku_17_right
    snippet: studio-rpc-usb-uart
    artifact-name: watahaku_17_right_peripheral
    
  - board: bmp_boost
    shield: watahaku_17_left
    snippet: studio-rpc-usb-uart
    artifact-name: watahaku_17_left_peripheral
  - board: bmp_boost
    shield: watahaku_17_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: watahaku_17_right_central

  - board: bmp_boost
    shield: watahaku_17_left
    snippet: "studio-rpc-usb-uart split-trackball"
    artifact-name: watahaku_17_double_ball_left_peripheral
  - board: bmp_boost
    shield: watahaku_17_right
    snippet: "studio-rpc-usb-uart split-trackball-listner"
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: watahaku_17_double_ball_right_central

  - board: bmp_boost
    shield: settings_reset