# Draw keymap diagrams using keymap-drawer
name: Draw ZMK keymaps
on:
  workflow_dispatch:

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: 'config/*.keymap'
      config_path: 'keymap-drawer/config.yaml'
      output_folder: 'keymap-drawer'
      amend_commit: true
      json_path: 'keymap-drawer/layouts'
